# dm-gzh-api-zuul-dev
spring:
  application:
    name: dm-gzh-api-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-user:
      path: /api/user/**
      serviceId: dm-gzh-web-user